updates to work with windows
mftcodes/projectbowen pull request #9
Opened 2024-02-26 13:27 UTC by AllisonBolen

#Summary: 
- update readme to include dbeaver mention 
- update envconfig.go to work on windows

#Justification: 
- we paired on setup and you had me use dbeaver to access the database
- the envconfig.go file had issues running the MkDir command so I updated it to MkDirAll

# Docs and Resources: 
- NA

2024-02-26 14:42 UTC, mftcodes requested changes
A couple comments to look at, otherwise this is great!

2024-02-26 14:42 UTC, mftcodes commented on README.md
> +   3. *there was a step here that I don't remember, something to do with drivers or ports????*
Under connection settings > driver properties > set `allowPublicKeyRetrieval` to `TRUE`

2024-02-26 14:42 UTC, mftcodes commented on config/envConfig.go
> +	err := os.MkdirAll(tempDir, 0750)
This is a great add and a clear miss on my part

2024-02-26 14:42 UTC, mftcodes commented on README.md
> +1. Setup MySQL in Docker
Rather than an ordered list item, maybe we should do a sub-header here?

2024-03-10 21:35 UTC, AllisonBolen commented on README.md
> +1. Setup MySQL in Docker
add as sub heading

2024-03-10 23:59 UTC, mftcodes approved these changes

2024-03-10 23:59 UTC, merged